pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        stage('Build - KAN-4') {
            steps {
                echo 'Jira issue KAN-4 is being updated through Jenkins Pipeline'
                dir('book-library/book-library') {
                    bat 'mvn clean package'
                }
            }
        }
    }

    post {
        success {
            jiraComment issueKey: 'KAN-4', body: 'Jenkins build completed successfully for KAN-4.'
        }
        failure {
            jiraComment issueKey: 'KAN-4', body: 'Jenkins build failed for KAN-4.'
        }
    }
}
