pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        stage('Build') {
            steps {
                dir('book-library/book-library') {
                    bat 'mvn clean package'
                }
            }
        }
    }
}
